"""Central Morning event dispatcher
=====================================
Maps Morning ``eventType`` strings to dedicated handler functions.

Usage (from webhooks_morning.py):

    from app.api.v1.payments.morning_handler import handle_morning_event
    return JSONResponse(handle_morning_event(body, parsed))

Adding a new event
------------------
1. Write a handler:  ``def handle_my_event(ctx: dict) -> dict``
2. Register it:      ``EVENT_HANDLERS['new-event/type'] = handle_my_event``

Context dict (``ctx``) keys
----------------------------
event_type    str    Morning eventType string
status        str    'SUCCESS' | 'FAILED' | 'UNKNOWN' | ...
amount        int    amount in NIS (0 if not present)
transaction_id str   Morning transaction/document ID
external_id   str    externalId / custom field (= our intake token for auto-tier)
client_name   str    customer display name
client_phone  str    customer phone (raw Morning format)
email         str    customer email
product_name  str    product / plan name from Morning
tier          str    'auto' | 'starter' | 'growth' | 'pro' | 'unknown'
raw           dict   full raw webhook body
"""
from __future__ import annotations

import logging
import threading
from typing import Callable

from app.core.config import settings
from app.services.morning_service import MorningService

logger = logging.getLogger(__name__)
_morning = MorningService()


# ═══════════════════════════════════════════════════════════════════════════════
# Context extraction
# ═══════════════════════════════════════════════════════════════════════════════

def _extract_context(body: dict, parsed: dict) -> dict:
    """Build a rich, flat context dict from raw + parsed webhook data."""
    return {
        'event_type':     parsed.get('type', 'unknown'),
        'status':         parsed.get('status', 'UNKNOWN'),
        'amount':         parsed.get('amount', 0),
        'transaction_id': parsed.get('transaction_id', ''),
        'external_id':    parsed.get('external_id') or '',
        'client_name':    parsed.get('client_name') or 'לקוח חדש',
        'client_phone':   parsed.get('client_phone') or '',
        'email':          parsed.get('email') or '',
        'product_name':   parsed.get('product_name') or '',
        'tier':           _morning.detect_tier(parsed.get('amount', 0)),
        'raw':            body,
    }


# ═══════════════════════════════════════════════════════════════════════════════
# Event handlers
# ═══════════════════════════════════════════════════════════════════════════════

def handle_order_paid(ctx: dict) -> dict:
    """
    ``sale-pages/order-paid`` — a payment was completed on a Morning sales page.

    • status != SUCCESS → ignore (Morning may send failed events too)
    • tier == 'auto'    → full automated deployment pipeline
    • tier in ('starter','growth','pro') → create pro_lead + admin WhatsApp alert
    """
    if ctx['status'] != 'SUCCESS':
        logger.info(
            '[MorningHandler][order-paid] Ignoring non-success status=%s txn=%s',
            ctx['status'], ctx['transaction_id'][:12],
        )
        return {'ok': True, 'detail': f'non-success status: {ctx["status"]}'}

    tier = ctx['tier']

    if tier == 'auto':
        return _order_paid_auto(ctx)

    if tier in ('starter', 'growth', 'pro'):
        return _order_paid_pro(ctx, tier)

    logger.warning(
        '[MorningHandler][order-paid] Unknown tier for amount=%s txn=%s',
        ctx['amount'], ctx['transaction_id'][:12],
    )
    return {'ok': True, 'detail': f'unknown amount {ctx["amount"]}'}


def handle_page_contacted(ctx: dict) -> dict:
    """
    ``sale-pages/page-contacted`` — someone filled the Morning sales-page contact form.
    They are *interested* but have NOT yet paid.

    1. Sends an admin WhatsApp "New Lead" alert immediately.
    2. Queues a Celery abandonment-recovery task (fires after 10 minutes).
       The task checks at send-time whether the lead has since converted
       and skips if so. The recovery message is generated by Grok when
       ``settings.xai_api_key`` is configured, otherwise uses a fixed template.
    """
    name    = ctx['client_name']
    phone   = ctx['client_phone']
    email   = ctx['email']
    product = ctx['product_name'] or 'לא ידוע'

    logger.info('[MorningHandler][page-contacted] Lead: %s phone=%s', name[:30], phone[:8])

    owner = settings.whatsapp_owner_phone
    if owner:
        msg = (
            f"🔔 *ליד חדש — TAZO-WEB*\n\n"
            f"👤 שם: *{name}*\n"
            f"📞 טלפון: {phone or 'לא זמין'}\n"
            f"📧 אימייל: {email or 'לא זמין'}\n"
            f"📦 מוצר: {product}\n\n"
            f"💡 מתעניין אך *טרם שילם* — צור קשר בהקדם!"
        )
        threading.Thread(
            target=_send_wa,
            args=(owner, msg, 'page-contacted'),
            daemon=True,
        ).start()

    # ── Queue abandonment-recovery message (10 minutes) ───────────────────
    if phone:
        try:
            from app.tasks import send_abandonment_recovery_task
            send_abandonment_recovery_task.apply_async(
                args=[name, phone],
                countdown=600,  # 10 minutes
            )
            logger.info(
                '[MorningHandler][page-contacted] Recovery task queued for %s*** (600 s)',
                phone[:6],
            )
        except Exception as exc:
            logger.warning(
                '[MorningHandler][page-contacted] Could not queue recovery task: %s', exc
            )

    return {'ok': True, 'detail': 'lead alert queued + recovery task scheduled'}


def handle_payment_received(ctx: dict) -> dict:
    """
    ``payment/received`` — any payment received event (not tied to a sales page).
    Logs the revenue and sends the admin a WhatsApp "passive income" toast.
    """
    amount  = ctx['amount']
    name    = ctx['client_name']
    txn_id  = ctx['transaction_id']
    product = ctx['product_name'] or 'לא ידוע'

    logger.info(
        '[MorningHandler][payment/received] amount=%s NIS from %s txn=%s',
        amount, name[:30], txn_id[:12],
    )

    owner = settings.whatsapp_owner_phone
    if owner:
        msg = (
            f"💰 *הכנסה פסיבית — TAZO-WEB*\n\n"
            f"💵 סכום: *{amount:,} ₪*\n"
            f"👤 לקוח: {name}\n"
            f"📦 מוצר: {product}\n"
            f"💳 עסקה: `{txn_id[:16]}...`\n\n"
            f"כסף נכנס ✅"
        )
        threading.Thread(
            target=_send_wa,
            args=(owner, msg, 'payment/received'),
            daemon=True,
        ).start()

    return {'ok': True, 'detail': 'revenue logged'}


def handle_file_infected(ctx: dict) -> dict:
    """
    ``file/infected`` — Morning detected a security threat in an uploaded file.
    Sends an *urgent* admin WhatsApp security alert immediately (blocking send
    so the alert isn't silently dropped if the process exits quickly).
    """
    name    = ctx['client_name']
    phone   = ctx['client_phone']
    email   = ctx['email']
    txn_id  = ctx['transaction_id']
    product = ctx['product_name'] or 'לא ידוע'

    logger.error(
        '[MorningHandler][file/infected] SECURITY ALERT — infected file detected '
        'client=%s txn=%s',
        name[:30], txn_id[:12],
    )

    owner = settings.whatsapp_owner_phone
    if owner:
        msg = (
            f"🚨 *התראת אבטחה — Morning זיהה קובץ נגוע!*\n\n"
            f"👤 לקוח: *{name}*\n"
            f"📞 טלפון: {phone or 'לא זמין'}\n"
            f"📧 אימייל: {email or 'לא זמין'}\n"
            f"📦 מוצר: {product}\n"
            f"💳 עסקה: `{txn_id[:16] or 'N/A'}...`\n\n"
            f"⚠️ *נדרשת פעולה מיידית!*\n"
            f"בדוק את לוח הבקרה של Morning ועצור את העסקה במידת הצורך."
        )
        # Blocking send — security alerts must not be dropped
        _send_wa(owner, msg, 'file/infected')

    return {'ok': True, 'detail': 'security alert sent'}


# ═══════════════════════════════════════════════════════════════════════════════
# Handler registry  ← add new events here
# ═══════════════════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════════════════
# TAZ wallet top-up handler
# ═══════════════════════════════════════════════════════════════════════════════

def handle_taz_wallet_topup(ctx: dict) -> dict:
    """
    TAZ wallet top-up via Morning payment link.
    externalId format: "taz-topup:{customer_phone}:{ref}"
    On SUCCESS: top up customer vault wallet, then complete any pending order.
    """
    if ctx["status"] != "SUCCESS":
        return {"ok": True, "detail": f"non-success: {ctx["status"]}"}

    external_id = ctx.get("external_id", "")
    if not external_id.startswith("taz-topup:"):
        return {"ok": True, "detail": "not a taz-topup event"}

    parts = external_id.split(":")
    if len(parts) < 3:
        logger.warning("[TazTopup] Bad externalId format: %s", external_id[:30])
        return {"ok": False, "detail": "bad externalId format"}

    customer_phone = parts[1]
    ref            = parts[2]
    amount_nis     = ctx["amount"]  # 1 ILS = 1 TAZ

    if amount_nis <= 0:
        return {"ok": False, "detail": "amount must be > 0"}

    try:
        from decimal import Decimal
        from app.db.session import SessionLocal
        from app.models.customer_taz_wallet import CustomerTazWallet
        from app.services.vault import vault_client as vault
        import json

        db = SessionLocal()
        try:
            wallet_rec = db.query(CustomerTazWallet).filter(CustomerTazWallet.phone == customer_phone).first()
            if not wallet_rec:
                logger.warning("[TazTopup] No wallet for phone %s", customer_phone[:6])
                return {"ok": False, "detail": "wallet not found"}

            result = vault.topup_wallet(wallet_rec.wallet_id, Decimal(str(amount_nis)), reference=ref)
            if not result:
                logger.error("[TazTopup] topup_wallet failed for %s", wallet_rec.wallet_id[:8])
                return {"ok": False, "detail": "vault topup failed"}

            logger.info("[TazTopup] Topped up wallet %s by %s TAZ", wallet_rec.wallet_id[:8], amount_nis)

            # Complete pending order if any
            pending = wallet_rec.pending_order_ref
            if pending:
                try:
                    order_data = json.loads(pending)
                    if order_data.get("ref") == ref:
                        _complete_pending_order(wallet_rec, order_data, db)
                        wallet_rec.pending_order_ref = None
                        db.commit()
                except Exception as exc:
                    logger.warning("[TazTopup] Could not complete pending order: %s", exc)

            return {"ok": True, "topped_up": amount_nis, "wallet_id": wallet_rec.wallet_id}
        finally:
            db.close()
    except Exception as exc:
        logger.exception("[TazTopup] Unexpected error: %s", exc)
        return {"ok": False, "detail": str(exc)}


def _complete_pending_order(wallet_rec, order_data: dict, db) -> None:
    """Complete an order that was pending TAZ top-up."""
    import httpx
    from decimal import Decimal
    from app.services.vault import vault_client as vault
    import re, os

    def clean(p):
        p = re.sub(r"D", "", p or "")
        return ("972" + p[1:]) if p.startswith("0") and len(p) == 10 else p

    total      = Decimal(str(order_data.get("total", 0)))
    biz_phone  = clean(order_data.get("business_phone", ""))
    order_id   = f"web-{wallet_rec.wallet_id[:8]}-{order_data["ref"]}"

    # Escrow lock
    lock = vault.escrow_lock(wallet_rec.wallet_id, order_id, total)
    if not lock:
        logger.warning("[TazTopup] escrow_lock failed for pending order %s", order_id)

    # Forward to tazo-sync
    sync_url = os.environ.get("TAZO_SYNC_URL", "https://tazo-sync.com") + "/api/orders"
    sync_key = os.environ.get("TAZO_SYNC_INTERNAL_KEY", "")
    try:
        r = httpx.post(
            sync_url,
            json={
                "source": "tazo-web-taz",
                "businessName": order_data.get("business_name", "עסק"),
                "business_phone": biz_phone,
                "buyerPhone": wallet_rec.phone,
                "customer_name": order_data.get("customer_name", "לקוח"),
                "items": order_data.get("items", []),
                "total": float(total),
                "order_type": order_data.get("order_type", "delivery"),
                "notes": order_data.get("notes", ""),
                "taz_order_id": order_id,
                "isShadowOrder": False,
            },
            headers={"Authorization": f"Bearer {sync_key}"},
            timeout=12,
        )
        logger.info("[TazTopup] tazo-sync response: %s", r.status_code)
    except Exception as exc:
        logger.warning("[TazTopup] tazo-sync forward failed: %s", exc)


EVENT_HANDLERS: dict[str, Callable[[dict], dict]] = {
    'sale-pages/order-paid':     handle_order_paid,
    'sale-pages/page-contacted': handle_page_contacted,
    'payment/received':          handle_payment_received,
    'file/infected':             handle_file_infected,
    'sale-pages/order-paid:taz':  handle_taz_wallet_topup,  # TAZ wallet top-up
}


# ═══════════════════════════════════════════════════════════════════════════════
# Main dispatcher
# ═══════════════════════════════════════════════════════════════════════════════

def handle_morning_event(body: dict, parsed: dict) -> dict:
    """
    Central Morning event dispatcher.

    Called by the ``POST /webhooks/morning`` endpoint after signature
    verification and payload parsing.  Routes to the appropriate handler
    based on ``eventType``.

    Unknown events with ``SUCCESS`` status fall back to the
    ``handle_order_paid`` handler for backward-compatibility.
    All other unknown events are acknowledged (200) and logged.
    """
    ctx        = _extract_context(body, parsed)
    event_type = ctx['event_type']

    handler = EVENT_HANDLERS.get(event_type)
    if handler:
        logger.info('[MorningHandler] Dispatching event=%s status=%s', event_type, ctx['status'])
        return handler(ctx)

    # TAZ top-up detection by externalId prefix (any event type)
    external_id = ctx.get('external_id', '')
    if external_id.startswith('taz-topup:'):
        logger.info('[MorningHandler] TAZ top-up detected via externalId=%s', external_id[:20])
        return handle_taz_wallet_topup(ctx)

    # Fallback: unknown event type
    if ctx['status'] == 'SUCCESS':
        logger.info(
            '[MorningHandler] Unknown event_type=%s with SUCCESS status — '
            'falling back to order_paid handler', event_type,
        )
        return handle_order_paid(ctx)

    logger.info('[MorningHandler] Unhandled event=%s status=%s — ack only', event_type, ctx['status'])
    return {'ok': True, 'detail': f'unhandled event: {event_type}'}


# ═══════════════════════════════════════════════════════════════════════════════
# Auto-tier helpers (called from handle_order_paid)
# ═══════════════════════════════════════════════════════════════════════════════

def _order_paid_auto(ctx: dict) -> dict:
    """39 NIS automated pipeline: mark intake as paid and queue Celery task."""
    import threading as _threading

    external_id = ctx['external_id']
    if not external_id:
        logger.warning('[MorningHandler][auto] No externalId — cannot correlate to intake')
        return {'ok': True, 'detail': 'no external_id'}

    from app.db.session import SessionLocal
    from app.models.public_intake import PublicIntake

    db = SessionLocal()
    try:
        intake = db.query(PublicIntake).filter(PublicIntake.token == external_id).first()
        if not intake:
            logger.warning('[MorningHandler][auto] Intake not found: token=%s', external_id[:8])
            return {'ok': True, 'detail': 'intake not found'}

        if intake.payment_status == 'paid':
            return {'ok': True, 'detail': 'already processed'}

        intake.payment_status    = 'paid'
        intake.payment_reference = ctx['transaction_id']
        intake.plan_tier         = 'auto'
        db.commit()
        logger.info('[MorningHandler][auto] Intake %s marked as paid', external_id[:8])

        domain        = intake.desired_domain or ''
        html_content  = intake.generated_html or ''
        phone         = intake.phone or ''
        business_name = intake.business_name or ''
        token         = intake.token
    finally:
        db.close()

    try:
        from app.tasks import finalize_deployment_task
        finalize_deployment_task.delay(token)
        logger.info('[MorningHandler][auto] finalize_deployment_task queued for token=%s', token[:8])
    except Exception as celery_exc:
        logger.warning(
            '[MorningHandler][auto] Celery unavailable (%s) — falling back to thread', celery_exc
        )
        # Import here to avoid circular imports at module load time
        from app.api.v1.routes.webhooks_morning import _activate_site_and_notify
        _threading.Thread(
            target=_activate_site_and_notify,
            args=(token, domain, html_content, phone, business_name),
            daemon=True,
        ).start()

    return {'ok': True}


def _order_paid_pro(ctx: dict, tier: str) -> dict:
    """299 / 699 / 1299 NIS manual onboarding: create pro_lead + notify admin."""
    import secrets as _secrets

    transaction_id = ctx['transaction_id']
    client_name    = ctx['client_name']
    client_phone   = ctx['client_phone']
    amount         = ctx['amount']

    from app.db.session import SessionLocal
    from app.models.public_intake import PublicIntake

    db = SessionLocal()
    token = ''
    try:
        existing = (
            db.query(PublicIntake)
            .filter(PublicIntake.payment_reference == transaction_id)
            .first()
        )
        if existing:
            logger.info(
                '[MorningHandler][%s] Transaction already recorded: txn=%s',
                tier, transaction_id[:12],
            )
            return {'ok': True, 'detail': 'already processed'}

        token = _secrets.token_urlsafe(32)
        intake = PublicIntake(
            token=token,
            business_name=client_name,
            phone=client_phone,
            status='pro_lead',
            payment_status='paid',
            payment_reference=transaction_id,
            plan_tier=tier,
        )
        db.add(intake)
        db.commit()
        logger.info(
            '[MorningHandler][%s] Pro lead created: token=%s client=%s',
            tier, token[:8], client_name[:30],
        )
    finally:
        db.close()

    # Notifications run outside DB session
    from app.api.v1.routes.webhooks_morning import _handle_pro_notifications
    threading.Thread(
        target=_handle_pro_notifications,
        args=(tier, client_name, client_phone, transaction_id, amount, token),
        daemon=True,
    ).start()

    return {'ok': True}


# ═══════════════════════════════════════════════════════════════════════════════
# Shared utility
# ═══════════════════════════════════════════════════════════════════════════════

def _send_wa(phone: str, message: str, label: str) -> None:
    """Fire-and-forget WhatsApp send with error logging."""
    try:
        from app.services.communications.meta_whatsapp_service import MetaWhatsAppService
        MetaWhatsAppService().send_text(phone, message)
        logger.info('[MorningHandler][%s] WhatsApp alert sent', label)
    except Exception as exc:
        logger.warning('[MorningHandler][%s] WhatsApp send failed: %s', label, exc)
